### ISSUE TITLE
摄像头锁定

### ISSUE THREAD

**Issue by forest-jj** [dreamcontinue/OpenCV_with_contrib_on_Android#1]
权限已经打开了，但是还是显示没有权限

**Comment by forest-jj** [comment]
``E/org.opencv.xfeatures2d: xfeatures2d::create_10() caught cv::Exception: OpenCV(4.1.0) /Users/sellmair/Sources/sellmair/opencv_contrib/modules/xfeatures2d/src/surf.cpp:1029: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'create'

**Comment by syt2** [comment]
权限问题我不清楚 我已经很久没用过安卓的了
第二个报错应该是因为版本问题，需要自己将nonfree模块编译进去，具体步骤可以自己去查一下
或者直接使用我这个仓库里的3.4.0版本，是已经编译了nonfree模块的

**Comment by forest-jj** [comment]
好的 谢谢 我自己编译解决了 ，我这出的错就是nonfree没有编译进去




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"梦的延续"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 上午10:02
收件人:&nbsp;"dreamcontinue/OpenCV_with_contrib_on_Android"<OpenCV_with_contrib_on_Android@noreply.github.com&gt;;
抄送:&nbsp;"生活"<346796040@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dreamcontinue/OpenCV_with_contrib_on_Android] 摄像头锁定 (#1)





 
权限问题我不清楚 我已经很久没用过安卓的了
 第二个报错应该是因为版本问题，需要自己将nonfree模块编译进去，具体步骤可以自己去查一下
 或者直接使用我这个仓库里的3.4.0版本，是已经编译了nonfree模块的
